/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccountStatus = "activation_pending" | "active" | "grace_period";

export type ActivationLinkKind = "account_activation" | "guest_invitation";

export type AgentStatus = "available" | "blocked";

export type AnonymizationStatus = "done" | "none" | "pending";

export type AuditAction = "account_created" | "account_updated" | "activation_link_resent" | "agent_blocked" | "agent_published" | "agent_reactivated" | "contract_archived" | "contract_created" | "contract_field_changed" | "contract_updated" | "device_revoked_by_admin";

export type ChatErasureReason = "agent_removed" | "device_revoked" | "logout";

export type ClassificationStatus = "classified" | "failed" | "pending";

export type CodeChannel = "email" | "sms";

export type CodePurpose = "access_recovery" | "device_verification" | "password_reset" | "validation_mailbox";

export type ConnectionStatus = "connected" | "partial" | "pending" | "reconnect_required" | "refused";

export type ConsentAction = "granted" | "withdrawn";

export type ConsentTrigger = "contract_details_deleted" | "user_action";

export type ContractFieldType = "amount" | "choice" | "date" | "text";

export type DecisionKind = "abandoned" | "pending" | "refused" | "validated";

export type DeliveryStatus = "failed" | "sending" | "sent";

export type DeviceType = "android" | "desktop" | "iphone" | "other";

export type ErasureStatus = "done" | "failed" | "pending";

export type ExecutionStatus = "failed" | "not_started" | "running" | "succeeded";

export type ExportStatus = "expired" | "failed" | "preparing" | "ready" | "requested";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type GraceOrigin = "billing_unsubscribe" | "in_app_request";

export type GuestRank = "core" | "secondary";

export type InfoDataType = "email" | "past_date" | "phone" | "postal_code" | "text";

export type InitialSetupStep = "completed" | "step_1_my_info" | "step_2_guest_info";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LegalDocumentType = "contract_challenge_consent" | "privacy_policy" | "terms_of_use";

export type LogbookEntryType = "action_done" | "action_refused" | "action_validated" | "request";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PromptKind = "example" | "first_suggestion";

export type ReportCategory = "incorrect_response" | "other" | "wrong_action";

export type RequirementOwner = "account" | "each_profile" | "primary_user";

export type ScanStatus = "clean" | "infected" | "pending";

export type SecurityEventType = "device_revoked" | "device_verified" | "login_email_changed" | "login_locked" | "password_changed" | "pattern_locked" | "pattern_recovered";

export type SessionEndReason = "account_grace_period" | "device_revoked" | "expired" | "guest_removed" | "logout";

export type SettingValueType = "email" | "integer";

export type SyncStatus = "failed" | "running" | "succeeded";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "guest" | "primary_user";

export type UserStatus = "active" | "grace_period" | "pending_activation" | "removed";

export interface AccountConnections {
  account_id: string;
  connected_by_user_id: string | null;
  connected_email: string;
  connector_type_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  /**
   * Mêmes valeurs que agent_connections.status. Le bandeau « Drive non connecté » des contrats se déduit de status différent de connected
   */
  status: Generated<ConnectionStatus>;
  status_changed_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
}

export interface AccountContracts {
  account_id: string;
  /**
   * État courant du consentement (la preuve est dans contract_consent_events). Remis à false par la suppression complète du contrat (US-35 RF5)
   */
  consent_active: Generated<boolean>;
  consent_changed_at: Timestamp | null;
  consent_changed_by_user_id: string | null;
  contract_definition_id: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  last_modified_at: Timestamp | null;
  last_modified_by_user_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Accounts {
  created_at: Generated<Timestamp>;
  /**
   * Nombre maximum de demandes aux agents par jour et par profil du compte (50 par défaut), fixé selon le plan et réglable par l'administrateur ; voir register_agent_request()
   */
  daily_request_limit: Generated<number>;
  /**
   * in_app_request = bouton Désabonnement (annulable immédiatement) ; billing_unsubscribe = outil de facturation (reprise = nouvel abonnement hors app) — US-59 RF2/RF3
   */
  grace_origin: GraceOrigin | null;
  grace_started_at: Timestamp | null;
  /**
   * Nombre maximum d'invités du plan. Une réduction du plan n'expulse personne (US-21 RF6) : seuls les ajouts sont bloqués
   */
  guest_quota: number;
  id: Generated<string>;
  /**
   * Date de suppression définitive (début du délai de grâce + 30 jours). Lue par le traitement quotidien (US-56 RT2)
   */
  purge_scheduled_at: Timestamp | null;
  /**
   * activation_pending = créé par l'admin, lien d'activation non utilisé ; grace_period = accès suspendu en attente de suppression
   */
  status: Generated<AccountStatus>;
  /**
   * Date de fin d'abonnement ; sert à calculer la fin de conservation du journal des consentements (5 ans, US-36 RT1)
   */
  subscription_ended_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface ActionDecisions {
  agent_id: Int8;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by_user_id: string | null;
  /**
   * pending = carte en attente ; abandoned = déconnexion ou expiration de l'historique sans décision (US-39 RF8)
   */
  decision: Generated<DecisionKind>;
  execution_status: Generated<ExecutionStatus>;
  external_action_ref: string;
  id: Generated<Int8>;
  requester_user_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ActivationLinks {
  created_at: Generated<Timestamp>;
  created_by_user_id: string | null;
  delivery_attempts: Generated<number>;
  /**
   * sending = Envoi en cours ; sent = Invitation envoyée ; failed = Échec d'envoi (US-18 RF7, RF12)
   */
  delivery_status: Generated<DeliveryStatus>;
  /**
   * Envoi + 30 minutes. Le statut « Invitation expirée » de l'écran invités se déduit de cette date
   */
  expires_at: Timestamp;
  id: Generated<Int8>;
  kind: ActivationLinkKind;
  revoked_at: Timestamp | null;
  sent_at: Timestamp | null;
  /**
   * true si un numéro était renseigné : l'invitation part aussi par SMS
   */
  sms_requested: Generated<boolean>;
  /**
   * Empreinte SHA-256 du jeton envoyé par email/SMS ; le jeton lui-même n'est jamais conservé
   */
  token_hash: Buffer;
  used_at: Timestamp | null;
  user_id: string;
}

export interface AdminAuditLog {
  action_type: AuditAction;
  admin_user_id: string | null;
  details: Json | null;
  entity_id: string;
  entity_type: string;
  id: Generated<Int8>;
  occurred_at: Generated<Timestamp>;
}

export interface AgentCategories {
  code: string;
  id: Generated<number>;
  is_core_only: Generated<boolean>;
  label: string;
  shown_on_dashboard: Generated<boolean>;
  sort_order: number;
}

export interface AgentConnections {
  agent_id: Int8;
  connected_email: string;
  connector_type_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  /**
   * pending = autorisation (ou code de vérification) en attente ; connected = utilisable ; refused/partial = consentement Google refusé/incomplet ; reconnect_required = autorisation expirée ou révoquée (US-13 RT3). Absence de ligne = « Non configuré »
   */
  status: Generated<ConnectionStatus>;
  status_changed_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AgentInfoFields {
  agent_id: Int8;
  created_at: Generated<Timestamp>;
  data_type: InfoDataType;
  id: Generated<Int8>;
  is_required: Generated<boolean>;
  label: string;
  /**
   * 1 = valeur unique ; supérieur à 1 = liste de valeurs (ex. contacts) limitée à ce nombre
   */
  max_items: Generated<number>;
  /**
   * Clé commune permettant de proposer une valeur déjà saisie pour un autre agent (même clé, même type de donnée) : voir v_info_prefill_suggestions
   */
  shared_key: string | null;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface AgentRequirements {
  agent_id: Int8;
  connector_type_id: number;
  /**
   * primary_user = seule l'utilisateur principal configure pour cet agent (l'invité voit « à configurer par X », US-29 RF3) ; each_profile = chaque profil connecte ses comptes ; account = connexion unique du compte (table account_connections), partagée par les agents qui l'exigent
   */
  owner_scope: Generated<RequirementOwner>;
}

export interface Agents {
  blocked_at: Timestamp | null;
  blocked_by_user_id: string | null;
  category_id: number;
  /**
   * Nombre maximum d'adresses en copie par profil que cet agent accepte, fixé par l'administrateur à la publication ; 0 = l'agent n'a pas de section « Adresses en copie » (US-16 RF1, RF4)
   */
  cc_addresses_max_count: Generated<number>;
  created_at: Generated<Timestamp>;
  /**
   * Identifiant de l'agent chez Digitorn, choisi parmi ceux hébergés et non encore publiés (US-45 RF2)
   */
  digitorn_agent_ref: string;
  full_description: string;
  id: Generated<Int8>;
  /**
   * Message affiché dans la bannière de blocage, 200 caractères max, obligatoire au blocage
   */
  maintenance_message: string | null;
  name: string;
  published_at: Generated<Timestamp>;
  published_by_user_id: string | null;
  short_description: string;
  /**
   * available = utilisable ; blocked = maintenance, MAAQ refuse toute nouvelle demande vers cet agent (US-42 RT1)
   */
  status: Generated<AgentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface AgentSamplePrompts {
  agent_id: Int8;
  content: string;
  id: Generated<Int8>;
  /**
   * example = exemple affiché sur la fiche et indexé par la recherche ; first_suggestion = bouton de l'état d'accueil du tchat (3 par agent)
   */
  kind: PromptKind;
  sort_order: Generated<number>;
}

export interface AgentValidatedActions {
  agent_id: Int8;
  id: Generated<Int8>;
  label: string;
  sort_order: Generated<number>;
}

export interface CcAddresses {
  agent_id: Int8;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  /**
   * Profil propriétaire : la liste de l'utilisateur principal ne s'applique qu'à SES événements (D5)
   */
  user_id: string;
}

export interface ChatErasureRequests {
  agent_id: Int8 | null;
  alerted_at: Timestamp | null;
  attempts: Generated<number>;
  completed_at: Timestamp | null;
  id: Generated<Int8>;
  last_attempt_at: Timestamp | null;
  last_error: string | null;
  reason: ChatErasureReason;
  requested_at: Generated<Timestamp>;
  status: Generated<ErasureStatus>;
  user_id: string;
}

export interface ConnectorTypes {
  code: string;
  id: Generated<number>;
  label: string;
  requires_oauth: boolean;
}

export interface ContractConsentEvents {
  /**
   * Identifiant du compte, SANS FK : référence conservée après suppression du compte (point à valider DPO, H14)
   */
  account_id: string;
  action_type: ConsentAction;
  /**
   * Empreinte HMAC-SHA256 de l'email du consentant (clé hors base) : preuve nominative après suppression du compte sans conserver l'email
   */
  actor_email_hash: Buffer;
  actor_user_id: string | null;
  contract_definition_id: Int8;
  id: Generated<Int8>;
  legal_version_id: Int8;
  occurred_at: Generated<Timestamp>;
  retain_until: Timestamp | null;
  trigger_reason: Generated<ConsentTrigger>;
}

export interface ContractDefinitions {
  /**
   * Contrat retiré de la liste par l'administrateur ; les données clients restent en base (hypothèse H8)
   */
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  sort_order: number;
  updated_at: Generated<Timestamp>;
}

export interface ContractDocuments {
  account_contract_id: Int8;
  added_at: Generated<Timestamp>;
  added_by_user_id: string | null;
  classification_attempts: Generated<number>;
  /**
   * pending = « Classement en cours » ; classified = « Document disponible » ; failed = « Classement impossible » après 3 essais auto (US-34 RF13, RF14)
   */
  classification_status: Generated<ClassificationStatus>;
  created_at: Generated<Timestamp>;
  drive_file_ref: string | null;
  file_name: string;
  id: Generated<Int8>;
  mime_type: string;
  /**
   * Analyse antivirus obligatoire avant disponibilité (US-34 RT2)
   */
  scan_status: Generated<ScanStatus>;
  size_bytes: Int8;
  staging_storage_key: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ContractFieldDefinitions {
  archived_at: Timestamp | null;
  contract_definition_id: Int8;
  created_at: Generated<Timestamp>;
  /**
   * text, date, amount (montant positif) ou choice (liste de choix, voir contract_field_options)
   */
  field_type: ContractFieldType;
  id: Generated<Int8>;
  is_required: Generated<boolean>;
  label: string;
  sort_order: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface ContractFieldOptions {
  field_definition_id: Int8;
  id: Generated<Int8>;
  label: string;
  sort_order: Generated<number>;
}

export interface ContractFieldValues {
  account_contract_id: Int8;
  field_definition_id: Int8;
  id: Generated<Int8>;
  updated_at: Generated<Timestamp>;
  updated_by_user_id: string | null;
  /**
   * Montant en euros (devise unique supposée, H9), jamais négatif
   */
  value_amount: Numeric | null;
  value_date: Timestamp | null;
  value_option_id: Int8 | null;
  value_text: string | null;
}

export interface DailyRequestCounters {
  /**
   * Nombre de demandes déjà acceptées ce jour-là ; borné par accounts.daily_request_limit via register_agent_request()
   */
  request_count: Generated<number>;
  /**
   * Jour calendaire dans le fuseau de l'appareil au moment de la demande (hypothèse H35)
   */
  request_date: Timestamp;
  user_id: string;
}

export interface DataExports {
  created_at: Generated<Timestamp>;
  download_expires_at: Timestamp | null;
  failure_reason: string | null;
  id: Generated<string>;
  ready_at: Timestamp | null;
  requested_at: Generated<Timestamp>;
  status: Generated<ExportStatus>;
  storage_key: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Devices {
  browser: string | null;
  created_at: Generated<Timestamp>;
  device_type: DeviceType;
  first_connected_at: Generated<Timestamp>;
  /**
   * Identifiant propre à MAAQ, généré à la vérification d'identité et conservé sur l'appareil
   */
  id: string;
  last_activity_at: Generated<Timestamp>;
  /**
   * Échecs consécutifs ; 3 = verrouillage. Remis à 0 après un schéma correct ou une récupération (US-6 RF8)
   */
  pattern_failed_count: Generated<number>;
  /**
   * Empreinte du schéma 3×3 (min. 4 points). NULL pour l'administrateur (pas de schéma) ou tant que non créé
   */
  pattern_hash: string | null;
  /**
   * Non NULL = accès par schéma verrouillé sur cet appareil ; le mot de passe reste utilisable (US-7 RF4)
   */
  pattern_locked_at: Timestamp | null;
  pattern_set_at: Timestamp | null;
  /**
   * Appareil révoqué : il disparaît de la liste et doit repasser par la vérification d'identité (US-53 RF3)
   */
  revoked_at: Timestamp | null;
  revoked_by_user_id: string | null;
  /**
   * Fuseau horaire IANA de l'appareil (ex. Europe/Paris), mis à jour à chaque connexion ; défaut Europe/Paris
   */
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ErasureTraces {
  completed_at: Timestamp | null;
  deleted_at: Generated<Timestamp>;
  digitorn_attempts: Generated<number>;
  digitorn_status: Generated<ErasureStatus>;
  digitorn_user_ref: string | null;
  former_account_id: string | null;
  former_role: UserRole;
  former_user_id: string;
  id: Generated<Int8>;
  last_attempt_at: Timestamp | null;
  last_error: string | null;
}

export interface ErrorReports {
  agent_id: Int8;
  category: ReportCategory;
  id: Generated<Int8>;
  message_ref: string;
  reported_at: Generated<Timestamp>;
  reporter_role: UserRole;
  reporter_user_id: string | null;
  request_text: string | null;
  /**
   * Copie de la réponse signalée (peut contenir des données personnelles : à chiffrer, voir plan de sécurité)
   */
  response_text: string;
  user_comment: string | null;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  idempotency_key: string;
  request_path: string;
  response_body: Json | null;
  response_status: number;
  user_id: string;
}

export interface LegalAcceptances {
  accepted_at: Generated<Timestamp>;
  id: Generated<Int8>;
  user_id: string;
  version_id: Int8;
}

export interface LegalDocumentVersions {
  /**
   * Texte intégral de la version (le nom du partenaire du consentement y figure : à fournir, US-36 RF2)
   */
  content: string;
  created_at: Generated<Timestamp>;
  document_type: LegalDocumentType;
  id: Generated<Int8>;
  /**
   * Date d'entrée en vigueur ; la version courante est la plus récente déjà publiée
   */
  published_at: Timestamp;
  version_label: string;
}

export interface LogbookEntries {
  account_id: string;
  agent_id: Int8;
  /**
   * pending = entrées masquées pendant l'anonymisation du texte (US-57 RF7) ; done = nom et données personnelles retirés (irréversible)
   */
  anonymization_status: Generated<AnonymizationStatus>;
  entry_type: LogbookEntryType;
  /**
   * Identifiant Digitorn de l'entrée, garantit l'idempotence de la synchronisation
   */
  external_ref: string;
  id: Generated<Int8>;
  occurred_at: Timestamp;
  /**
   * Demandeur ; NULL après suppression définitive de l'invité (affiché « Invité supprimé »)
   */
  requester_user_id: string | null;
  result: string | null;
  summary: string;
  synced_at: Generated<Timestamp>;
}

export interface LogbookEntryParticipants {
  entry_id: Int8;
  /**
   * Date de l'entrée du carnet (clé de partition, avec entry_id)
   */
  entry_occurred_at: Timestamp;
  user_id: string;
}

export interface LogbookSyncRuns {
  entries_imported: Generated<number>;
  error_message: string | null;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  started_at: Generated<Timestamp>;
  status: Generated<SyncStatus>;
}

export interface PlatformSettingChanges {
  changed_at: Generated<Timestamp>;
  changed_by_user_id: string | null;
  id: Generated<Int8>;
  new_value: string | null;
  old_value: string | null;
  setting_key: string;
}

export interface PlatformSettings {
  description: string;
  max_value: number | null;
  min_value: number | null;
  setting_key: string;
  updated_at: Generated<Timestamp>;
  updated_by_user_id: string | null;
  value_text: string | null;
  value_type: SettingValueType;
}

export interface ProfileAgents {
  added_at: Generated<Timestamp>;
  agent_id: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  /**
   * Date de retrait ; NULL = agent visible sur le dashboard/page Contrats. Ne compte plus dans la limite de 10
   */
  removed_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  name: string;
}

export interface SecurityEvents {
  /**
   * Auteur de l'action quand il diffère du profil concerné (ex. utilisateur principal révoquant l'appareil d'un invité)
   */
  actor_user_id: string | null;
  details: Json | null;
  device_id: string | null;
  /**
   * Type d'événement : verrouillage du schéma ou du mot de passe, récupération, appareil vérifié ou révoqué, changement d'email ou de mot de passe
   */
  event_type: SecurityEventType;
  id: Generated<Int8>;
  occurred_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  device_id: string;
  expires_at: Timestamp;
  id: Generated<string>;
  last_seen_at: Generated<Timestamp>;
  revoked_at: Timestamp | null;
  revoked_reason: SessionEndReason | null;
  /**
   * Empreinte du jeton de session : une session copiée ne vaut plus rien une fois invalidée (US-9 RT1)
   */
  token_hash: Buffer;
  user_id: string;
}

export interface UserAgentInfoValues {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  info_field_id: Int8;
  item_position: Generated<number>;
  updated_at: Generated<Timestamp>;
  /**
   * Profil ayant fait la dernière modification (traçabilité, US-12 RT1)
   */
  updated_by_user_id: string | null;
  user_id: string;
  value_encrypted: Buffer;
}

export interface Users {
  /**
   * Compte d'appartenance ; NULL pour les administrateurs (hors compte client)
   */
  account_id: string | null;
  activated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  deletion_requested_at: Timestamp | null;
  /**
   * Identifiant de ce profil chez Digitorn (format à valider avec Digitorn, hypothèse H11)
   */
  digitorn_user_ref: string | null;
  /**
   * Email de connexion, unique et insensible à la casse. Pour un invité actif, sa modification change aussi l'email de connexion (US-19 RF4)
   */
  email: string;
  failed_login_count: Generated<number>;
  first_name: string;
  /**
   * core = invité 1 (premier invité ajouté, ou désigné par l'utilisateur principal) ; secondary = invités 2 à n (D1, D6)
   */
  guest_rank: GuestRank | null;
  id: Generated<string>;
  /**
   * Étape de la configuration initiale (utilisateur principal) pour reprendre là où il s'est arrêté ; NULL pour invités et admins
   */
  initial_setup_step: InitialSetupStep | null;
  last_name: string;
  /**
   * Fin du blocage de 15 min après 5 échecs consécutifs de mot de passe (US-3 RF4)
   */
  login_locked_until: Timestamp | null;
  password_hash: string | null;
  /**
   * Téléphone mobile pour SMS (invitation, code de vérification). Distinct du téléphone saisi pour les agents (US-19 RF5)
   */
  phone: string | null;
  /**
   * Date de suppression définitive des données du profil : délai de grâce de 30 jours (auto-suppression, durée unique décidée le 01/10/2026) ou X jours après retrait (US-20 RT2, paramètre de la console)
   */
  purge_scheduled_at: Timestamp | null;
  removed_at: Timestamp | null;
  role: UserRole;
  /**
   * pending_activation = invitation/activation en attente ; active ; grace_period = suppression demandée par le profil ; removed = invité retiré, données purgées après X jours
   */
  status: Generated<UserStatus>;
  updated_at: Generated<Timestamp>;
}

export interface VAccountGuestQuota {
  account_id: string | null;
  guest_quota: number | null;
  guests_used: Int8 | null;
  places_left: Int8 | null;
}

export interface VDashboardAgents {
  added_at: Timestamp | null;
  agent_id: Int8 | null;
  category_code: string | null;
  display_status: string | null;
  name: string | null;
  short_description: string | null;
  user_id: string | null;
}

export interface VerificationCodes {
  agent_connection_id: Int8 | null;
  channel: CodeChannel;
  code_hash: Buffer;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  /**
   * Identifiant d'appareil proposé par le client, devient devices.id après un code correct
   */
  device_identifier: string | null;
  expires_at: Timestamp;
  failed_attempts: Generated<number>;
  id: Generated<Int8>;
  invalidated_at: Timestamp | null;
  /**
   * device_verification (10 min) ; access_recovery (30 min) ; validation_mailbox (vérification de la boîte, US-15) ; password_reset = hypothèse H5 (US-3 renvoie vers un parcours non décrit)
   */
  purpose: CodePurpose;
  target: string;
  user_id: string;
}

export interface VGuestDisplayStatus {
  account_id: string | null;
  display_status: string | null;
  guest_rank: GuestRank | null;
  last_invitation_sent_at: Timestamp | null;
  user_id: string | null;
}

export interface VInfoPrefillSuggestions {
  info_field_id: Int8 | null;
  item_position: number | null;
  source_field_id: Int8 | null;
  user_id: string | null;
  value_encrypted: Buffer | null;
}

export interface VNeverActivatedPurgeCandidates {
  account_id: string | null;
  last_activity_at: Timestamp | null;
  role: UserRole | null;
  user_id: string | null;
}

export interface VProfileAgentMissingItems {
  agent_id: Int8 | null;
  item_code: string | null;
  item_kind: string | null;
  responsible: string | null;
  user_id: string | null;
}

export interface DB {
  account_connections: AccountConnections;
  account_contracts: AccountContracts;
  accounts: Accounts;
  action_decisions: ActionDecisions;
  activation_links: ActivationLinks;
  admin_audit_log: AdminAuditLog;
  agent_categories: AgentCategories;
  agent_connections: AgentConnections;
  agent_info_fields: AgentInfoFields;
  agent_requirements: AgentRequirements;
  agent_sample_prompts: AgentSamplePrompts;
  agent_validated_actions: AgentValidatedActions;
  agents: Agents;
  cc_addresses: CcAddresses;
  chat_erasure_requests: ChatErasureRequests;
  connector_types: ConnectorTypes;
  contract_consent_events: ContractConsentEvents;
  contract_definitions: ContractDefinitions;
  contract_documents: ContractDocuments;
  contract_field_definitions: ContractFieldDefinitions;
  contract_field_options: ContractFieldOptions;
  contract_field_values: ContractFieldValues;
  daily_request_counters: DailyRequestCounters;
  data_exports: DataExports;
  devices: Devices;
  erasure_traces: ErasureTraces;
  error_reports: ErrorReports;
  idempotency_keys: IdempotencyKeys;
  legal_acceptances: LegalAcceptances;
  legal_document_versions: LegalDocumentVersions;
  logbook_entries: LogbookEntries;
  logbook_entry_participants: LogbookEntryParticipants;
  logbook_sync_runs: LogbookSyncRuns;
  platform_setting_changes: PlatformSettingChanges;
  platform_settings: PlatformSettings;
  profile_agents: ProfileAgents;
  schema_migrations: SchemaMigrations;
  security_events: SecurityEvents;
  sessions: Sessions;
  user_agent_info_values: UserAgentInfoValues;
  users: Users;
  v_account_guest_quota: VAccountGuestQuota;
  v_dashboard_agents: VDashboardAgents;
  v_guest_display_status: VGuestDisplayStatus;
  v_info_prefill_suggestions: VInfoPrefillSuggestions;
  v_never_activated_purge_candidates: VNeverActivatedPurgeCandidates;
  v_profile_agent_missing_items: VProfileAgentMissingItems;
  verification_codes: VerificationCodes;
}
